#! /bin/sh
#
#  $Id: wdays 0.02 1996/09/10 00:00:02 tom Exp $
#
#  wdays:  Uses `wdays.sed' for filtering `gcal %mon -Cdl7+ -H::: ...'
#            output so only all working days of the complete week,
#            except holidays, and the succeeding Monday are displayed.
#            Use `-Cdl14+' if you need an overview of two weeks.
#
#  UN*X solution.
#
#  Copyright (C) 1996  Thomas Esken      <esken@uni-muenster.de>
#                      Im Hagenfeld 84
#                      D-48147 M"unster
#                      GERMANY
#
#  This software doesn't claim completeness, correctness or usability.
#  On principle I will not be liable for ANY damages or losses (implicit
#  or explicit), which result from using or handling my software.
#  If you use this software, you agree without any exception to this
#  agreement, which binds you LEGALLY !!
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the `GNU General Public License' as published by
#  the `Free Software Foundation'; either version 2, or (at your option)
#  any later version.
#
#  You should have received a copy of the `GNU General Public License'
#  along with this program; if not, write to the:
#
#    Free Software Foundation, Inc.
#    59 Temple Place - Suite 330
#    Boston, MA 02111-1307,  USA
#
gcal %mon -Cdl7+ -H::: $* | sed -f wdays.sed
