#! /bin/sh

# Automatically generated by mksamp-1.sed from demo-1a.in.

echo "$ LANGUAGE=en gcal -H no -u -x -f ./demo-1.rc 1996+2002"
LANGUAGE=en GCAL= GCALPATH=. ../../../src/gcal -H no -u -x -f ./demo-1.rc $* 1996+2002

exit 0
