#! /bin/sh

# Automatically generated by mksamp-1.sed from lbrk-1a.in.

echo "$ gcal %00000101 --resource-file=./lbrk-1.rc --disable-highlighting"
LANGUAGE=de GCAL= GCALPATH=. ../../../src/gcal %00000101 --resource-file=./lbrk-1.rc --disable-highlighting $*

exit 0
