#! /bin/sh

# Automatically generated by mksamp-1.sed from tvar-2a.in.

echo "$ gcal %19960101 -H no -x -f ./tvar-2.rc"
LANGUAGE=de GCAL= GCALPATH=. ../../../src/gcal %19960101 -H no -x -f ./tvar-2.rc $*

echo "$ gcal %19960101 -H no -x -f ./tvar-2.rc -y"
LANGUAGE=de GCAL= GCALPATH=. ../../../src/gcal %19960101 -H no -x -f ./tvar-2.rc -y $*

exit 0
